version: '3.9'

services:
    nginx:
        image: nginx:1.23.3
        container_name: nginx_api_gateway_nginx
        ports:
            - 8080:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./logs:/var/log/nginx
