version: '3.9'

services:
    nginx:
        image: nginx:1.23.3
        network_mode: host
        container_name: nginx_api_gateway_nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./logs:/var/log/nginx
