version: '3.9'

services:
    app_1:
        container_name: nginx_api_gateway_app_1
        network_mode: host
        build:
            context: ./apps/app-1
            dockerfile: Dockerfile
    app_2:
        container_name: nginx_api_gateway_app_2
        network_mode: host
        build:
            context: ./apps/app-2
            dockerfile: Dockerfile
